############################################
## Configuration file for Photo Promenade ##
############################################

#
# Enter a title and a subtitle for your gallery
#

title: Photo Promenade
subtitle: A tiny PHP photo gallery

#
# Define the desired output sizes.
#
# The default sizes used by Photo Promenade are called "big" and "thumb",
# but you can create more named sizes if you want to.
#
# Sizes are specified textually using a "width x height" syntax. Aspect 
# ratios are always kept intact.
#
# 640x480  will resize images to fit within these dimensions
#     640  will resize them to a fixed width of 640 pixels and a variable height
#    x480  will resize them to a fixed height of 480 pixels and a variable height
#

sizes:
  big: x480
  thumb: x80