############################################
## Configuration file for Photo Promenade ##
############################################

#
# Enter a title and a subtitle for your gallery
#

title: Photo Promenade
subtitle: A tiny PHP photo gallery
author: Peter Gassner, Benjamin Wiederkehr

#
# Define the desired output sizes.
#
# The default sizes used by Photo Promenade are called "big" and "thumb",
# but you can create more named sizes if you want to.
#
# Sizes can be specified using either width or height or both.
# The aspect ratio will be kept.
#

sizes:
  big:
    height: 480
  thumb:
    height: 80

#
# If you have mod-rewrite, you can uncomment this line
# to get nice URLs.

nice_urls: true